#ifndef PMBUS_CFG_COMMON_H
#define PMBUS_CFG_COMMON_H

#define PMBUS_ADDRESS_7BIT_BASE               0x58U
#define PMBUS_ALERT_RESPONSE_ADDRESS_7BIT     0x0CU
#define PMBUS_ARP_DEFAULT_ADDRESS_7BIT        0x61U
#define PMBUS_ZONE_READ_ADDRESS_7BIT          0x28U
#define PMBUS_ZONE_WRITE_ADDRESS_7BIT         0x37U

#define PMBUS_ADDRESS_STRAP_00_7BIT           0x58U
#define PMBUS_ADDRESS_STRAP_01_7BIT           0x59U
#define PMBUS_ADDRESS_STRAP_10_7BIT           0x5AU
#define PMBUS_ADDRESS_STRAP_11_7BIT           0x5BU
#define PMBUS_ADDRESS_INVALID_FALLBACK_7BIT   PMBUS_ADDRESS_STRAP_10_7BIT

#define PMBUS_ADDRESS_7BIT_TO_WRITE(addr7)    ((unsigned char)((addr7) << 1))
#define PMBUS_ADDRESS_7BIT_TO_READ(addr7)     ((unsigned char)(((addr7) << 1) | 0x01U))

#define PMBUS_RX_BUFFER_SIZE                  40U
#define PMBUS_TX_BUFFER_SIZE                  34U
#define PMBUS_MAX_BLOCK_SIZE                  32U
#define PMBUS_DEBUG_QUEUE_SIZE                16U

#define PMBUS_PROFILE_MINIMAL                 1U
#define PMBUS_PROFILE_FULL                    2U

/*
    Profile selection:
    - PMBUS_PROFILE_FULL keeps the full PoC command surface enabled.
    - PMBUS_PROFILE_MINIMAL keeps the common discovery, status,
      basic telemetry, and MFR identity commands for smaller flash targets.
    Individual PMBUS_ENABLE_CMD_* switches may still be overridden by the
    compiler command line or a platform config before this file is included.
*/
#ifndef PMBUS_PROFILE
#define PMBUS_PROFILE                         PMBUS_PROFILE_FULL
#endif

#if (PMBUS_PROFILE == PMBUS_PROFILE_MINIMAL)
#define PMBUS_PROFILE_DEFAULT_CMD_CORE        1U
#define PMBUS_PROFILE_DEFAULT_CMD_STATUS      1U
#define PMBUS_PROFILE_DEFAULT_CMD_TELEMETRY   1U
#define PMBUS_PROFILE_DEFAULT_CMD_LIMITS      0U
#define PMBUS_PROFILE_DEFAULT_CMD_FAN         0U
#define PMBUS_PROFILE_DEFAULT_CMD_ENERGY      0U
#define PMBUS_PROFILE_DEFAULT_CMD_MFR_BASIC   1U
#define PMBUS_PROFILE_DEFAULT_CMD_MFR_EXT     0U
#define PMBUS_PROFILE_DEFAULT_CMD_PAGE_PLUS   0U
#define PMBUS_PROFILE_DEFAULT_CMD_ZONE        0U
#define PMBUS_PROFILE_DEFAULT_CMD_POLICY      0U
#define PMBUS_PROFILE_DEFAULT_CMD_FWUPLOAD    0U
#define PMBUS_PROFILE_DEFAULT_ARP             0U
#define PMBUS_PROFILE_DEFAULT_ZONE_ALIAS      0U
#else
#define PMBUS_PROFILE_DEFAULT_CMD_CORE        1U
#define PMBUS_PROFILE_DEFAULT_CMD_STATUS      1U
#define PMBUS_PROFILE_DEFAULT_CMD_TELEMETRY   1U
#define PMBUS_PROFILE_DEFAULT_CMD_LIMITS      1U
#define PMBUS_PROFILE_DEFAULT_CMD_FAN         1U
#define PMBUS_PROFILE_DEFAULT_CMD_ENERGY      1U
#define PMBUS_PROFILE_DEFAULT_CMD_MFR_BASIC   1U
#define PMBUS_PROFILE_DEFAULT_CMD_MFR_EXT     1U
#define PMBUS_PROFILE_DEFAULT_CMD_PAGE_PLUS   1U
#define PMBUS_PROFILE_DEFAULT_CMD_ZONE        1U
#define PMBUS_PROFILE_DEFAULT_CMD_POLICY      1U
#define PMBUS_PROFILE_DEFAULT_CMD_FWUPLOAD    1U
#define PMBUS_PROFILE_DEFAULT_ARP             1U
#define PMBUS_PROFILE_DEFAULT_ZONE_ALIAS      1U
#endif

#ifndef PMBUS_ENABLE_CMD_CORE
#define PMBUS_ENABLE_CMD_CORE                 PMBUS_PROFILE_DEFAULT_CMD_CORE
#endif

#ifndef PMBUS_ENABLE_CMD_STATUS
#define PMBUS_ENABLE_CMD_STATUS               PMBUS_PROFILE_DEFAULT_CMD_STATUS
#endif

#ifndef PMBUS_ENABLE_CMD_TELEMETRY
#define PMBUS_ENABLE_CMD_TELEMETRY            PMBUS_PROFILE_DEFAULT_CMD_TELEMETRY
#endif

#ifndef PMBUS_ENABLE_CMD_LIMITS
#define PMBUS_ENABLE_CMD_LIMITS               PMBUS_PROFILE_DEFAULT_CMD_LIMITS
#endif

#ifndef PMBUS_ENABLE_CMD_FAN
#define PMBUS_ENABLE_CMD_FAN                  PMBUS_PROFILE_DEFAULT_CMD_FAN
#endif

#ifndef PMBUS_ENABLE_CMD_ENERGY
#define PMBUS_ENABLE_CMD_ENERGY               PMBUS_PROFILE_DEFAULT_CMD_ENERGY
#endif

#ifndef PMBUS_ENABLE_CMD_MFR_BASIC
#define PMBUS_ENABLE_CMD_MFR_BASIC            PMBUS_PROFILE_DEFAULT_CMD_MFR_BASIC
#endif

#ifndef PMBUS_ENABLE_CMD_MFR_EXT
#define PMBUS_ENABLE_CMD_MFR_EXT              PMBUS_PROFILE_DEFAULT_CMD_MFR_EXT
#endif

#ifndef PMBUS_ENABLE_CMD_PAGE_PLUS
#define PMBUS_ENABLE_CMD_PAGE_PLUS            PMBUS_PROFILE_DEFAULT_CMD_PAGE_PLUS
#endif

#ifndef PMBUS_ENABLE_CMD_ZONE
#define PMBUS_ENABLE_CMD_ZONE                 PMBUS_PROFILE_DEFAULT_CMD_ZONE
#endif

#ifndef PMBUS_ENABLE_CMD_POLICY
#define PMBUS_ENABLE_CMD_POLICY               PMBUS_PROFILE_DEFAULT_CMD_POLICY
#endif

#ifndef PMBUS_ENABLE_CMD_FWUPLOAD
#define PMBUS_ENABLE_CMD_FWUPLOAD             PMBUS_PROFILE_DEFAULT_CMD_FWUPLOAD
#endif

#define PMBUS_PEC_POLICY_DISABLED             0U
#define PMBUS_PEC_POLICY_OPTIONAL             1U
#define PMBUS_PEC_POLICY_REQUIRED             2U
#define PMBUS_PEC_POLICY                      PMBUS_PEC_POLICY_OPTIONAL
#define PMBUS_ENABLE_PEC                      ((PMBUS_PEC_POLICY) != PMBUS_PEC_POLICY_DISABLED)
#define PMBUS_DEBUG_ENABLE                    1U
#define PMBUS_DEBUG_PRINT_RX_FRAME            1U
#define PMBUS_DEBUG_PRINT_TX_READY            1U
#define PMBUS_DEBUG_PRINT_TX_DECODE           1U
#define PMBUS_DEBUG_PRINT_WRITE_DONE          1U
#define PMBUS_DEBUG_PRINT_STATUS              0U
#define PMBUS_ENABLE_SLAVE_RECOVER            1U
#define PMBUS_ENABLE_ARA_ALIAS                1U

#ifndef PMBUS_ENABLE_ARP
#define PMBUS_ENABLE_ARP                      PMBUS_PROFILE_DEFAULT_ARP
#endif

#ifndef PMBUS_ENABLE_ZONE_ALIAS
#define PMBUS_ENABLE_ZONE_ALIAS               PMBUS_PROFILE_DEFAULT_ZONE_ALIAS
#endif

#define PMBUS_I2C_ALIAS_SLOT_DISABLED         0xFFU
#define PMBUS_I2C_ALIAS_SLOT_ARA              1U
#define PMBUS_I2C_ALIAS_SLOT_ARP              2U
#define PMBUS_I2C_ALIAS_SLOT_ZONE_READ        3U
#define PMBUS_I2C_ALIAS_SLOT_ZONE_WRITE       PMBUS_I2C_ALIAS_SLOT_DISABLED

#define PMBUS_STATUS_BYTE_BUSY                       0x80U
#define PMBUS_STATUS_BYTE_OFF                        0x40U
#define PMBUS_STATUS_BYTE_VOUT_OV_FAULT              0x20U
#define PMBUS_STATUS_BYTE_IOUT_OC_FAULT              0x10U
#define PMBUS_STATUS_BYTE_VIN_UV_FAULT               0x08U
#define PMBUS_STATUS_BYTE_TEMPERATURE                0x04U
#define PMBUS_STATUS_BYTE_CML                        0x02U
#define PMBUS_STATUS_BYTE_NONE_OF_THE_ABOVE          0x01U

#define PMBUS_STATUS_WORD_VOUT                       0x8000U
#define PMBUS_STATUS_WORD_IOUT_POUT                  0x4000U
#define PMBUS_STATUS_WORD_INPUT                      0x2000U
#define PMBUS_STATUS_WORD_MFR_SPECIFIC               0x1000U
#define PMBUS_STATUS_WORD_PG_STATUS                  0x0800U
#define PMBUS_STATUS_WORD_FANS                       0x0400U
#define PMBUS_STATUS_WORD_OTHER                      0x0200U
#define PMBUS_STATUS_WORD_UNKNOWN                    0x0100U
#define PMBUS_STATUS_WORD_LOW_BYTE_CML               0x0002U

#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_COMMAND_RECEIVED 0x80U
#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_DATA_RECEIVED    0x40U
#define PMBUS_STATUS_CML_PACKET_ERROR_CHECK_FAILED               0x20U
#define PMBUS_STATUS_CML_MEMORY_FAULT_DETECTED                   0x10U
#define PMBUS_STATUS_CML_PROCESSOR_FAULT_DETECTED                0x08U
#define PMBUS_STATUS_CML_OTHER_COMMUNICATION_FAULT               0x02U
#define PMBUS_STATUS_CML_OTHER_MEMORY_OR_LOGIC_FAULT             0x01U

#define PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT         0x20U
#define PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT         0x10U
#define PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT            0x08U
#define PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT            0x04U
#define PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT             0x02U
#define PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT              0x01U

#define PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS                       0xFFU

#define PMBUS_STATUS_VOUT_VOUT_OV_FAULT               0x80U
#define PMBUS_STATUS_VOUT_VOUT_OV_WARNING             0x40U
#define PMBUS_STATUS_VOUT_VOUT_UV_WARNING             0x20U
#define PMBUS_STATUS_VOUT_VOUT_UV_FAULT               0x10U
#define PMBUS_STATUS_VOUT_VOUT_MAX_MIN_WARNING        0x08U
#define PMBUS_STATUS_VOUT_TON_MAX_FAULT               0x04U
#define PMBUS_STATUS_VOUT_TOFF_MAX_WARNING            0x02U
#define PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR         0x01U

#define PMBUS_STATUS_IOUT_IOUT_OC_FAULT               0x80U
#define PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT            0x40U
#define PMBUS_STATUS_IOUT_IOUT_OC_WARNING             0x20U
#define PMBUS_STATUS_IOUT_IOUT_UC_FAULT               0x10U
#define PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT         0x08U
#define PMBUS_STATUS_IOUT_IN_POWER_LIMITING_MODE      0x04U
#define PMBUS_STATUS_IOUT_POUT_OP_FAULT               0x02U
#define PMBUS_STATUS_IOUT_POUT_OP_WARNING             0x01U

#define PMBUS_STATUS_INPUT_VIN_OV_FAULT                         0x80U
#define PMBUS_STATUS_INPUT_VIN_OV_WARNING                       0x40U
#define PMBUS_STATUS_INPUT_VIN_UV_WARNING                       0x20U
#define PMBUS_STATUS_INPUT_VIN_UV_FAULT                         0x10U
#define PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE 0x08U
#define PMBUS_STATUS_INPUT_IIN_OC_FAULT                         0x04U
#define PMBUS_STATUS_INPUT_IIN_OC_WARNING                       0x02U
#define PMBUS_STATUS_INPUT_PIN_OP_WARNING                       0x01U

#define PMBUS_STATUS_TEMPERATURE_OT_FAULT            0x80U
#define PMBUS_STATUS_TEMPERATURE_OT_WARNING          0x40U
#define PMBUS_STATUS_TEMPERATURE_UT_WARNING          0x20U
#define PMBUS_STATUS_TEMPERATURE_UT_FAULT            0x10U

#define PMBUS_STATUS_FANS_1_2_FAN_1_FAULT            0x80U
#define PMBUS_STATUS_FANS_1_2_FAN_2_FAULT            0x40U
#define PMBUS_STATUS_FANS_1_2_FAN_1_WARNING          0x20U
#define PMBUS_STATUS_FANS_1_2_FAN_2_WARNING          0x10U
#define PMBUS_STATUS_FANS_1_2_FAN_1_SPEED_OVERRIDDEN 0x08U
#define PMBUS_STATUS_FANS_1_2_FAN_2_SPEED_OVERRIDDEN 0x04U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT          0x02U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_WARNING        0x01U

#define PMBUS_STATUS_VOUT_FAULT_MASK                 (PMBUS_STATUS_VOUT_VOUT_OV_FAULT | PMBUS_STATUS_VOUT_VOUT_UV_FAULT | PMBUS_STATUS_VOUT_TON_MAX_FAULT | PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR)
#define PMBUS_STATUS_IOUT_FAULT_MASK                 (PMBUS_STATUS_IOUT_IOUT_OC_FAULT | PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT | PMBUS_STATUS_IOUT_IOUT_UC_FAULT | PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT | PMBUS_STATUS_IOUT_POUT_OP_FAULT)
#define PMBUS_STATUS_INPUT_FAULT_MASK                (PMBUS_STATUS_INPUT_VIN_OV_FAULT | PMBUS_STATUS_INPUT_VIN_UV_FAULT | PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE | PMBUS_STATUS_INPUT_IIN_OC_FAULT)
#define PMBUS_STATUS_TEMPERATURE_FAULT_MASK          (PMBUS_STATUS_TEMPERATURE_OT_FAULT | PMBUS_STATUS_TEMPERATURE_UT_FAULT)
#define PMBUS_STATUS_FANS_1_2_FAULT_MASK             (PMBUS_STATUS_FANS_1_2_FAN_1_FAULT | PMBUS_STATUS_FANS_1_2_FAN_2_FAULT | PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT)
#define PMBUS_STATUS_CML_FAULT_MASK                  0xFFU
#define PMBUS_STATUS_OTHER_FAULT_MASK                (PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT)
#define PMBUS_STATUS_MFR_SPECIFIC_FAULT_MASK         PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS

#define PMBUS_BLACKBOX_BLOCK_SIZE                    32U

#define PMBUS_FWUPLOAD_STATUS_COMPLETE               0x0001U
#define PMBUS_FWUPLOAD_STATUS_IN_PROGRESS            0x0002U
#define PMBUS_FWUPLOAD_STATUS_BAD_IMAGE              0x0004U
#define PMBUS_FWUPLOAD_STATUS_UNSUPPORTED            0x0010U

#define PMBUS_FWUPLOAD_HEADER_SIZE                   4U
#define PMBUS_FWUPLOAD_FLAG_FINAL_BLOCK              0x01U

#define PMBUS_I2C_BUS_CLEAR_PULSES                   9U
#define PMBUS_I2C_BUS_CLEAR_RETRY_COUNT              3U
#define PMBUS_I2C_RECOVER_MAX_ATTEMPTS               3U
#define PMBUS_I2C_RECOVER_BACKOFF_CYCLES             2U
#define PMBUS_I2C_STUCK_BUS_RETRY_CYCLES             8U
#define PMBUS_I2C_TIMEOUT_RECOVER_THRESHOLD          1U
#define PMBUS_I2C_BUS_ERROR_RECOVER_THRESHOLD        1U

#define PMBUS_I2C_STATUS_BUS_ERROR                   0x00U
#define PMBUS_I2C_STATUS_SLA_W_ACK                   0x60U
#define PMBUS_I2C_STATUS_DATA_RX_ACK                 0x80U
#define PMBUS_I2C_STATUS_DATA_RX_NACK                0x88U
#define PMBUS_I2C_STATUS_STOP_RESTART                0xA0U
#define PMBUS_I2C_STATUS_SLA_R_ACK                   0xA8U
#define PMBUS_I2C_STATUS_DATA_TX_ACK                 0xB8U
#define PMBUS_I2C_STATUS_DATA_TX_NACK                0xC0U
#define PMBUS_I2C_STATUS_LAST_TX_ACK                 0xC8U

#endif
