#ifndef PMBUS_CFG_COMMON_H
#define PMBUS_CFG_COMMON_H

#define PMBUS_ADDRESS_7BIT_BASE               0x58U
#define PMBUS_ALERT_RESPONSE_ADDRESS_7BIT     0x0CU

#define PMBUS_ADDRESS_STRAP_00_7BIT           0x58U
#define PMBUS_ADDRESS_STRAP_01_7BIT           0x59U
#define PMBUS_ADDRESS_STRAP_10_7BIT           0x5AU
#define PMBUS_ADDRESS_STRAP_11_7BIT           0x5BU
#define PMBUS_ADDRESS_INVALID_FALLBACK_7BIT   PMBUS_ADDRESS_STRAP_10_7BIT

#define PMBUS_ADDRESS_7BIT_TO_WRITE(addr7)    ((unsigned char)((addr7) << 1))
#define PMBUS_ADDRESS_7BIT_TO_READ(addr7)     ((unsigned char)(((addr7) << 1) | 0x01U))

#define PMBUS_RX_BUFFER_SIZE                  40U
#define PMBUS_TX_BUFFER_SIZE                  34U
#define PMBUS_MAX_BLOCK_SIZE                  32U
#define PMBUS_DEBUG_QUEUE_SIZE                16U

#define PMBUS_ENABLE_PEC                      1U
#define PMBUS_DEBUG_ENABLE                    1U
#define PMBUS_DEBUG_PRINT_RX_FRAME            1U
#define PMBUS_DEBUG_PRINT_TX_READY            1U
#define PMBUS_DEBUG_PRINT_TX_DECODE           1U
#define PMBUS_DEBUG_PRINT_WRITE_DONE          1U
#define PMBUS_DEBUG_PRINT_STATUS              0U
#define PMBUS_ENABLE_SLAVE_RECOVER            1U
#define PMBUS_ENABLE_ARA_ALIAS                1U

#define PMBUS_STATUS_BYTE_BUSY                       0x80U
#define PMBUS_STATUS_BYTE_OFF                        0x40U
#define PMBUS_STATUS_BYTE_VOUT_OV_FAULT              0x20U
#define PMBUS_STATUS_BYTE_IOUT_OC_FAULT              0x10U
#define PMBUS_STATUS_BYTE_VIN_UV_FAULT               0x08U
#define PMBUS_STATUS_BYTE_TEMPERATURE                0x04U
#define PMBUS_STATUS_BYTE_CML                        0x02U
#define PMBUS_STATUS_BYTE_NONE_OF_THE_ABOVE          0x01U

#define PMBUS_STATUS_WORD_VOUT                       0x8000U
#define PMBUS_STATUS_WORD_IOUT_POUT                  0x4000U
#define PMBUS_STATUS_WORD_INPUT                      0x2000U
#define PMBUS_STATUS_WORD_MFR_SPECIFIC               0x1000U
#define PMBUS_STATUS_WORD_PG_STATUS                  0x0800U
#define PMBUS_STATUS_WORD_FANS                       0x0400U
#define PMBUS_STATUS_WORD_OTHER                      0x0200U
#define PMBUS_STATUS_WORD_UNKNOWN                    0x0100U
#define PMBUS_STATUS_WORD_LOW_BYTE_CML               0x0002U

#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_COMMAND_RECEIVED 0x80U
#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_DATA_RECEIVED    0x40U
#define PMBUS_STATUS_CML_PACKET_ERROR_CHECK_FAILED               0x20U
#define PMBUS_STATUS_CML_MEMORY_FAULT_DETECTED                   0x10U
#define PMBUS_STATUS_CML_PROCESSOR_FAULT_DETECTED                0x08U
#define PMBUS_STATUS_CML_OTHER_COMMUNICATION_FAULT               0x02U
#define PMBUS_STATUS_CML_OTHER_MEMORY_OR_LOGIC_FAULT             0x01U

#define PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT         0x20U
#define PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT         0x10U
#define PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT            0x08U
#define PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT            0x04U
#define PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT             0x02U
#define PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT              0x01U

#define PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS                       0xFFU

#define PMBUS_STATUS_VOUT_VOUT_OV_FAULT               0x80U
#define PMBUS_STATUS_VOUT_VOUT_OV_WARNING             0x40U
#define PMBUS_STATUS_VOUT_VOUT_UV_WARNING             0x20U
#define PMBUS_STATUS_VOUT_VOUT_UV_FAULT               0x10U
#define PMBUS_STATUS_VOUT_VOUT_MAX_MIN_WARNING        0x08U
#define PMBUS_STATUS_VOUT_TON_MAX_FAULT               0x04U
#define PMBUS_STATUS_VOUT_TOFF_MAX_WARNING            0x02U
#define PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR         0x01U

#define PMBUS_STATUS_IOUT_IOUT_OC_FAULT               0x80U
#define PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT            0x40U
#define PMBUS_STATUS_IOUT_IOUT_OC_WARNING             0x20U
#define PMBUS_STATUS_IOUT_IOUT_UC_FAULT               0x10U
#define PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT         0x08U
#define PMBUS_STATUS_IOUT_IN_POWER_LIMITING_MODE      0x04U
#define PMBUS_STATUS_IOUT_POUT_OP_FAULT               0x02U
#define PMBUS_STATUS_IOUT_POUT_OP_WARNING             0x01U

#define PMBUS_STATUS_INPUT_VIN_OV_FAULT                         0x80U
#define PMBUS_STATUS_INPUT_VIN_OV_WARNING                       0x40U
#define PMBUS_STATUS_INPUT_VIN_UV_WARNING                       0x20U
#define PMBUS_STATUS_INPUT_VIN_UV_FAULT                         0x10U
#define PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE 0x08U
#define PMBUS_STATUS_INPUT_IIN_OC_FAULT                         0x04U
#define PMBUS_STATUS_INPUT_IIN_OC_WARNING                       0x02U
#define PMBUS_STATUS_INPUT_PIN_OP_WARNING                       0x01U

#define PMBUS_STATUS_TEMPERATURE_OT_FAULT            0x80U
#define PMBUS_STATUS_TEMPERATURE_OT_WARNING          0x40U
#define PMBUS_STATUS_TEMPERATURE_UT_WARNING          0x20U
#define PMBUS_STATUS_TEMPERATURE_UT_FAULT            0x10U

#define PMBUS_STATUS_FANS_1_2_FAN_1_FAULT            0x80U
#define PMBUS_STATUS_FANS_1_2_FAN_2_FAULT            0x40U
#define PMBUS_STATUS_FANS_1_2_FAN_1_WARNING          0x20U
#define PMBUS_STATUS_FANS_1_2_FAN_2_WARNING          0x10U
#define PMBUS_STATUS_FANS_1_2_FAN_1_SPEED_OVERRIDDEN 0x08U
#define PMBUS_STATUS_FANS_1_2_FAN_2_SPEED_OVERRIDDEN 0x04U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT          0x02U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_WARNING        0x01U

#define PMBUS_STATUS_VOUT_FAULT_MASK                 (PMBUS_STATUS_VOUT_VOUT_OV_FAULT | PMBUS_STATUS_VOUT_VOUT_UV_FAULT | PMBUS_STATUS_VOUT_TON_MAX_FAULT | PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR)
#define PMBUS_STATUS_IOUT_FAULT_MASK                 (PMBUS_STATUS_IOUT_IOUT_OC_FAULT | PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT | PMBUS_STATUS_IOUT_IOUT_UC_FAULT | PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT | PMBUS_STATUS_IOUT_POUT_OP_FAULT)
#define PMBUS_STATUS_INPUT_FAULT_MASK                (PMBUS_STATUS_INPUT_VIN_OV_FAULT | PMBUS_STATUS_INPUT_VIN_UV_FAULT | PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE | PMBUS_STATUS_INPUT_IIN_OC_FAULT)
#define PMBUS_STATUS_TEMPERATURE_FAULT_MASK          (PMBUS_STATUS_TEMPERATURE_OT_FAULT | PMBUS_STATUS_TEMPERATURE_UT_FAULT)
#define PMBUS_STATUS_FANS_1_2_FAULT_MASK             (PMBUS_STATUS_FANS_1_2_FAN_1_FAULT | PMBUS_STATUS_FANS_1_2_FAN_2_FAULT | PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT)
#define PMBUS_STATUS_CML_FAULT_MASK                  0xFFU
#define PMBUS_STATUS_OTHER_FAULT_MASK                (PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT)
#define PMBUS_STATUS_MFR_SPECIFIC_FAULT_MASK         PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS

#define PMBUS_BLACKBOX_BLOCK_SIZE                    32U

#define PMBUS_FWUPLOAD_STATUS_COMPLETE               0x0001U
#define PMBUS_FWUPLOAD_STATUS_IN_PROGRESS            0x0002U
#define PMBUS_FWUPLOAD_STATUS_BAD_IMAGE              0x0004U
#define PMBUS_FWUPLOAD_STATUS_UNSUPPORTED            0x0010U

#define PMBUS_FWUPLOAD_HEADER_SIZE                   4U
#define PMBUS_FWUPLOAD_FLAG_FINAL_BLOCK              0x01U

#define PMBUS_I2C_BUS_CLEAR_PULSES                   9U
#define PMBUS_I2C_BUS_CLEAR_RETRY_COUNT              3U
#define PMBUS_I2C_RECOVER_MAX_ATTEMPTS               3U
#define PMBUS_I2C_RECOVER_BACKOFF_CYCLES             2U
#define PMBUS_I2C_STUCK_BUS_RETRY_CYCLES             8U
#define PMBUS_I2C_TIMEOUT_RECOVER_THRESHOLD          1U
#define PMBUS_I2C_BUS_ERROR_RECOVER_THRESHOLD        1U

#define PMBUS_I2C_STATUS_BUS_ERROR                   0x00U
#define PMBUS_I2C_STATUS_SLA_W_ACK                   0x60U
#define PMBUS_I2C_STATUS_DATA_RX_ACK                 0x80U
#define PMBUS_I2C_STATUS_DATA_RX_NACK                0x88U
#define PMBUS_I2C_STATUS_STOP_RESTART                0xA0U
#define PMBUS_I2C_STATUS_SLA_R_ACK                   0xA8U
#define PMBUS_I2C_STATUS_DATA_TX_ACK                 0xB8U
#define PMBUS_I2C_STATUS_DATA_TX_NACK                0xC0U
#define PMBUS_I2C_STATUS_LAST_TX_ACK                 0xC8U

#endif
