#ifndef PMBUS_APP_H
#define PMBUS_APP_H
#include "pmbus_types.h"

typedef struct
{
    unsigned char power_good_asserted;
    unsigned char mfr_fault_active;
    unsigned char status_vout_source;
    unsigned char status_iout_source;
    unsigned char status_input_source;
    unsigned char status_temperature_source;
    unsigned char status_cml_source;
    unsigned char status_other_source;
    unsigned char status_mfr_specific_source;
    unsigned char status_fans_1_2_source;
} pmbus_platform_status_t;

typedef pmbus_platform_status_t *(*pmbus_platform_status_reader_t)(void);

void pmbus_app_init(void);
void pmbus_app_background_task(void);
void pmbus_app_register_platform_status_reader(pmbus_platform_status_reader_t reader);
void pmbus_app_apply_platform_status(pmbus_platform_status_t *platform_status);
unsigned char pmbus_app_detect_slave_address_7bit(void);
void pmbus_app_set_slave_address_7bit(unsigned char value);
unsigned char pmbus_app_get_slave_address_7bit(void);
unsigned char pmbus_app_get_address_valid(void);

void pmbus_app_clear_faults(void);
void pmbus_app_set_busy_state(unsigned char busy);
void pmbus_app_set_power_good_state(unsigned char asserted);
void pmbus_app_set_mfr_fault_state(unsigned char asserted);
void pmbus_app_set_comm_recovery_state(unsigned char last_reason, unsigned char recover_count, unsigned char recover_fail_count, unsigned char bus_released);
void pmbus_app_set_status_cml(unsigned char mask);
void pmbus_app_update_status_cml_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_cml_source(unsigned char active_bits);
void pmbus_app_set_status_vout(unsigned char value);
void pmbus_app_set_status_iout(unsigned char value);
void pmbus_app_set_status_input(unsigned char value);
void pmbus_app_set_status_temperature(unsigned char value);
void pmbus_app_set_status_fans_1_2(unsigned char value);
void pmbus_app_set_status_other(unsigned char value);
void pmbus_app_set_status_mfr_specific(unsigned char value);
void pmbus_app_update_status_vout_source(unsigned char active_bits);
void pmbus_app_update_status_iout_source(unsigned char active_bits);
void pmbus_app_update_status_input_source(unsigned char active_bits);
void pmbus_app_update_status_temperature_source(unsigned char active_bits);
void pmbus_app_update_status_fans_1_2_source(unsigned char active_bits);
void pmbus_app_update_status_other_source(unsigned char active_bits);
void pmbus_app_update_status_mfr_specific_source(unsigned char active_bits);
void pmbus_app_set_vout_fault_sources(unsigned char vout_ov_fault, unsigned char vout_ov_warning, unsigned char vout_uv_warning, unsigned char vout_uv_fault, unsigned char vout_max_min_warning, unsigned char ton_max_fault, unsigned char toff_max_warning, unsigned char vout_tracking_error);
void pmbus_app_set_iout_fault_sources(unsigned char iout_oc_fault, unsigned char iout_oc_lv_fault, unsigned char iout_oc_warning, unsigned char iout_uc_fault, unsigned char current_share_fault, unsigned char in_power_limiting_mode, unsigned char pout_op_fault, unsigned char pout_op_warning);
void pmbus_app_set_input_fault_sources(unsigned char vin_ov_fault, unsigned char vin_ov_warning, unsigned char vin_uv_warning, unsigned char vin_uv_fault, unsigned char unit_off_for_insufficient_input_voltage, unsigned char iin_oc_fault, unsigned char iin_oc_warning, unsigned char pin_op_warning);
void pmbus_app_set_temperature_fault_sources(unsigned char ot_fault, unsigned char ot_warning, unsigned char ut_warning, unsigned char ut_fault);
void pmbus_app_set_fans_1_2_fault_sources(unsigned char fan_1_fault, unsigned char fan_2_fault, unsigned char fan_1_warning, unsigned char fan_2_warning, unsigned char fan_1_speed_overridden, unsigned char fan_2_speed_overridden, unsigned char airflow_fault, unsigned char airflow_warning);
void pmbus_app_set_status_other_fault_sources(unsigned char input_a_fuse_or_breaker_fault, unsigned char input_b_fuse_or_breaker_fault, unsigned char input_a_oring_device_fault, unsigned char input_b_oring_device_fault, unsigned char output_oring_device_fault, unsigned char first_to_assert_smbalert);
void pmbus_app_set_cml_fault_sources(unsigned char invalid_or_unsupported_command_received, unsigned char invalid_or_unsupported_data_received, unsigned char packet_error_check_failed, unsigned char memory_fault_detected, unsigned char processor_fault_detected, unsigned char other_communication_fault, unsigned char other_memory_or_logic_fault);
void pmbus_app_update_status_vout_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_iout_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_input_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_temperature_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_fans_1_2_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_other_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_update_status_mfr_specific_bits(unsigned char set_mask, unsigned char clear_mask);
void pmbus_app_latch_blackbox(void);

void pmbus_app_update_input_source(unsigned long vin_mv, unsigned long iin_ma, unsigned long pin_mw);
void pmbus_app_update_output_source(unsigned long vout_mv, unsigned long iout_ma, unsigned long pout_mw);
void pmbus_app_update_temperature_source(unsigned long temp1_mc, unsigned long temp2_mc, unsigned long temp3_mc);
void pmbus_app_update_fan_source(unsigned long fan1_rpm, unsigned long fan2_rpm);

unsigned char pmbus_app_get_page(void);
void pmbus_app_set_page(unsigned char value);
void pmbus_app_record_page_plus_write(unsigned char page, unsigned char command, unsigned char *data_ptr, unsigned char length);
void pmbus_app_record_page_plus_read(unsigned char page, unsigned char command);
void pmbus_app_record_store_restore(unsigned char command, unsigned char code);

unsigned char pmbus_app_get_operation(void);
void pmbus_app_set_operation(unsigned char value);

unsigned char pmbus_app_get_on_off_config(void);
void pmbus_app_set_on_off_config(unsigned char value);
unsigned char pmbus_app_get_phase(void);
void pmbus_app_set_phase(unsigned char value);
unsigned char pmbus_app_get_write_protect(void);
void pmbus_app_set_write_protect(unsigned char value);

unsigned char pmbus_app_get_fan_config_1_2(void);
void pmbus_app_set_fan_config_1_2(unsigned char value);
uint16_t pmbus_app_get_fan_command_1(void);
void pmbus_app_set_fan_command_1(uint16_t value);
uint16_t pmbus_app_get_fan_command_2(void);
void pmbus_app_set_fan_command_2(uint16_t value);
unsigned char pmbus_app_get_fan_config_3_4(void);
void pmbus_app_set_fan_config_3_4(unsigned char value);
uint16_t pmbus_app_get_fan_command_3(void);
void pmbus_app_set_fan_command_3(uint16_t value);
uint16_t pmbus_app_get_fan_command_4(void);
void pmbus_app_set_fan_command_4(uint16_t value);

unsigned char pmbus_app_get_vout_mode(void);
void pmbus_app_set_vout_mode(unsigned char value);

uint16_t pmbus_app_get_vout_ov_fault_limit(void);
void pmbus_app_set_vout_ov_fault_limit(uint16_t value);
uint16_t pmbus_app_get_vout_ov_warn_limit(void);
void pmbus_app_set_vout_ov_warn_limit(uint16_t value);
uint16_t pmbus_app_get_vout_uv_warn_limit(void);
void pmbus_app_set_vout_uv_warn_limit(uint16_t value);
uint16_t pmbus_app_get_vout_uv_fault_limit(void);
void pmbus_app_set_vout_uv_fault_limit(uint16_t value);
uint16_t pmbus_app_get_iout_oc_fault_limit(void);
void pmbus_app_set_iout_oc_fault_limit(uint16_t value);
uint16_t pmbus_app_get_iout_oc_lv_fault_limit(void);
void pmbus_app_set_iout_oc_lv_fault_limit(uint16_t value);
uint16_t pmbus_app_get_iout_oc_warn_limit(void);
void pmbus_app_set_iout_oc_warn_limit(uint16_t value);
uint16_t pmbus_app_get_iout_uc_fault_limit(void);
void pmbus_app_set_iout_uc_fault_limit(uint16_t value);
uint16_t pmbus_app_get_ot_fault_limit(void);
void pmbus_app_set_ot_fault_limit(uint16_t value);
uint16_t pmbus_app_get_ot_warn_limit(void);
void pmbus_app_set_ot_warn_limit(uint16_t value);
uint16_t pmbus_app_get_ut_warn_limit(void);
void pmbus_app_set_ut_warn_limit(uint16_t value);
uint16_t pmbus_app_get_ut_fault_limit(void);
void pmbus_app_set_ut_fault_limit(uint16_t value);
uint16_t pmbus_app_get_vin_ov_fault_limit(void);
void pmbus_app_set_vin_ov_fault_limit(uint16_t value);
uint16_t pmbus_app_get_vin_ov_warn_limit(void);
void pmbus_app_set_vin_ov_warn_limit(uint16_t value);
uint16_t pmbus_app_get_vin_uv_warn_limit(void);
void pmbus_app_set_vin_uv_warn_limit(uint16_t value);
uint16_t pmbus_app_get_vin_uv_fault_limit(void);
void pmbus_app_set_vin_uv_fault_limit(uint16_t value);
uint16_t pmbus_app_get_iin_oc_fault_limit(void);
void pmbus_app_set_iin_oc_fault_limit(uint16_t value);
uint16_t pmbus_app_get_iin_oc_warn_limit(void);
void pmbus_app_set_iin_oc_warn_limit(uint16_t value);
unsigned char pmbus_app_get_vout_ov_fault_response(void);
void pmbus_app_set_vout_ov_fault_response(unsigned char value);
unsigned char pmbus_app_get_vout_uv_fault_response(void);
void pmbus_app_set_vout_uv_fault_response(unsigned char value);
unsigned char pmbus_app_get_iout_oc_fault_response(void);
void pmbus_app_set_iout_oc_fault_response(unsigned char value);
unsigned char pmbus_app_get_iout_oc_lv_fault_response(void);
void pmbus_app_set_iout_oc_lv_fault_response(unsigned char value);
unsigned char pmbus_app_get_iout_uc_fault_response(void);
void pmbus_app_set_iout_uc_fault_response(unsigned char value);
unsigned char pmbus_app_get_ot_fault_response(void);
void pmbus_app_set_ot_fault_response(unsigned char value);
unsigned char pmbus_app_get_ut_fault_response(void);
void pmbus_app_set_ut_fault_response(unsigned char value);
unsigned char pmbus_app_get_vin_ov_fault_response(void);
void pmbus_app_set_vin_ov_fault_response(unsigned char value);
unsigned char pmbus_app_get_vin_uv_fault_response(void);
void pmbus_app_set_vin_uv_fault_response(unsigned char value);
unsigned char pmbus_app_get_iin_oc_fault_response(void);
void pmbus_app_set_iin_oc_fault_response(unsigned char value);
unsigned char pmbus_app_get_ton_max_fault_response(void);
void pmbus_app_set_ton_max_fault_response(unsigned char value);
unsigned char pmbus_app_get_pout_op_fault_response(void);
void pmbus_app_set_pout_op_fault_response(unsigned char value);
uint16_t pmbus_app_get_zone_config(void);
void pmbus_app_set_zone_config(uint16_t value);
uint16_t pmbus_app_get_zone_active(void);
void pmbus_app_set_zone_active(uint16_t value);

uint16_t pmbus_app_get_vout_command(void);
void pmbus_app_set_vout_command(uint16_t value);
uint16_t pmbus_app_get_vout_trim(void);
void pmbus_app_set_vout_trim(uint16_t value);
uint16_t pmbus_app_get_vout_cal_offset(void);
void pmbus_app_set_vout_cal_offset(uint16_t value);
uint16_t pmbus_app_get_vout_max(void);
void pmbus_app_set_vout_max(uint16_t value);
uint16_t pmbus_app_get_vout_margin_high(void);
void pmbus_app_set_vout_margin_high(uint16_t value);
uint16_t pmbus_app_get_vout_margin_low(void);
void pmbus_app_set_vout_margin_low(uint16_t value);
uint16_t pmbus_app_get_vout_transition_rate(void);
void pmbus_app_set_vout_transition_rate(uint16_t value);
uint16_t pmbus_app_get_vout_droop(void);
void pmbus_app_set_vout_droop(uint16_t value);
uint16_t pmbus_app_get_vout_scale_loop(void);
void pmbus_app_set_vout_scale_loop(uint16_t value);
uint16_t pmbus_app_get_vout_scale_monitor(void);
void pmbus_app_set_vout_scale_monitor(uint16_t value);
uint16_t pmbus_app_get_vout_min(void);
void pmbus_app_set_vout_min(uint16_t value);
unsigned char pmbus_app_get_coefficients(unsigned char requested_command, unsigned char **data_ptr);
uint16_t pmbus_app_get_pout_max(void);
void pmbus_app_set_pout_max(uint16_t value);
uint16_t pmbus_app_get_max_duty(void);
void pmbus_app_set_max_duty(uint16_t value);
uint16_t pmbus_app_get_frequency_switch(void);
void pmbus_app_set_frequency_switch(uint16_t value);
unsigned char pmbus_app_get_power_mode(void);
void pmbus_app_set_power_mode(unsigned char value);
uint16_t pmbus_app_get_vin_on(void);
void pmbus_app_set_vin_on(uint16_t value);
uint16_t pmbus_app_get_vin_off(void);
void pmbus_app_set_vin_off(uint16_t value);
uint16_t pmbus_app_get_interleave(void);
void pmbus_app_set_interleave(uint16_t value);
uint16_t pmbus_app_get_iout_cal_gain(void);
void pmbus_app_set_iout_cal_gain(uint16_t value);
uint16_t pmbus_app_get_iout_cal_offset(void);
void pmbus_app_set_iout_cal_offset(uint16_t value);
uint16_t pmbus_app_get_power_good_on(void);
void pmbus_app_set_power_good_on(uint16_t value);
uint16_t pmbus_app_get_power_good_off(void);
void pmbus_app_set_power_good_off(uint16_t value);
uint16_t pmbus_app_get_ton_delay(void);
void pmbus_app_set_ton_delay(uint16_t value);
uint16_t pmbus_app_get_ton_rise(void);
void pmbus_app_set_ton_rise(uint16_t value);
uint16_t pmbus_app_get_ton_max_fault_limit(void);
void pmbus_app_set_ton_max_fault_limit(uint16_t value);
uint16_t pmbus_app_get_toff_delay(void);
void pmbus_app_set_toff_delay(uint16_t value);
uint16_t pmbus_app_get_toff_fall(void);
void pmbus_app_set_toff_fall(uint16_t value);
uint16_t pmbus_app_get_toff_max_warn_limit(void);
void pmbus_app_set_toff_max_warn_limit(uint16_t value);
uint16_t pmbus_app_get_pout_op_fault_limit(void);
void pmbus_app_set_pout_op_fault_limit(uint16_t value);
uint16_t pmbus_app_get_pout_op_warn_limit(void);
void pmbus_app_set_pout_op_warn_limit(uint16_t value);
uint16_t pmbus_app_get_pin_op_warn_limit(void);
void pmbus_app_set_pin_op_warn_limit(uint16_t value);
uint16_t pmbus_app_get_smbalert_mask(void);
void pmbus_app_set_smbalert_mask(uint16_t value);

unsigned char pmbus_app_get_capability(void);
unsigned char pmbus_app_get_status_byte(void);
uint16_t pmbus_app_get_status_word(void);
unsigned char pmbus_app_get_status_vout(void);
unsigned char pmbus_app_get_status_iout(void);
unsigned char pmbus_app_get_status_input(void);
unsigned char pmbus_app_get_status_temperature(void);
unsigned char pmbus_app_get_status_cml(void);
unsigned char pmbus_app_get_status_other(void);
unsigned char pmbus_app_get_status_mfr_specific(void);
unsigned char pmbus_app_get_status_fans_1_2(void);

unsigned char pmbus_app_get_read_ein(unsigned char **data_ptr);
unsigned char pmbus_app_get_read_eout(unsigned char **data_ptr);
uint16_t pmbus_app_get_read_vin(void);
uint16_t pmbus_app_get_read_iin(void);
uint16_t pmbus_app_get_read_vout(void);
uint16_t pmbus_app_get_read_iout(void);
uint16_t pmbus_app_get_read_temperature_1(void);
uint16_t pmbus_app_get_read_temperature_2(void);
uint16_t pmbus_app_get_read_temperature_3(void);
uint16_t pmbus_app_get_read_fan_speed_1(void);
uint16_t pmbus_app_get_read_fan_speed_2(void);
uint16_t pmbus_app_get_read_pout(void);
uint16_t pmbus_app_get_read_pin(void);
unsigned char pmbus_app_get_pmbus_revision(void);

unsigned char pmbus_app_get_mfr_id(unsigned char **data_ptr);
unsigned char pmbus_app_get_mfr_model(unsigned char **data_ptr);
unsigned char pmbus_app_get_mfr_revision(unsigned char **data_ptr);
unsigned char pmbus_app_get_mfr_serial(unsigned char **data_ptr);
unsigned char pmbus_app_get_mfr_blackbox(unsigned char **data_ptr);
unsigned char pmbus_app_get_mfr_cold_redundancy_config(void);
void pmbus_app_set_mfr_cold_redundancy_config(unsigned char value);
unsigned char pmbus_app_get_mfr_fwupload_mode(void);
void pmbus_app_set_mfr_fwupload_mode(unsigned char value);
uint16_t pmbus_app_get_mfr_fwupload_status(void);
unsigned char pmbus_app_store_mfr_fwupload_block(unsigned char *data_ptr, unsigned char length);

unsigned char pmbus_app_is_alert_asserted(void);
void pmbus_app_assert_alert(void);
void pmbus_app_release_alert(void);

#endif
