#ifndef PMBUS_PROTOCOL_H
#define PMBUS_PROTOCOL_H

/*
    Fixed PMBus/SMBus protocol constants.
    These values map to protocol-defined status bits or MCU I2C state codes;
    they are not user configuration knobs.
*/

#define PMBUS_COMMAND_PAGE                         0x00U
#define PMBUS_COMMAND_OPERATION                    0x01U
#define PMBUS_COMMAND_ON_OFF_CONFIG                0x02U
#define PMBUS_COMMAND_CLEAR_FAULTS                 0x03U
#define PMBUS_COMMAND_PHASE                        0x04U
#define PMBUS_COMMAND_PAGE_PLUS_WRITE              0x05U
#define PMBUS_COMMAND_PAGE_PLUS_READ               0x06U
#define PMBUS_COMMAND_ZONE_CONFIG                  0x07U
#define PMBUS_COMMAND_ZONE_ACTIVE                  0x08U
#define PMBUS_COMMAND_WRITE_PROTECT                0x10U
#define PMBUS_COMMAND_STORE_DEFAULT_ALL            0x11U
#define PMBUS_COMMAND_RESTORE_DEFAULT_ALL          0x12U
#define PMBUS_COMMAND_STORE_DEFAULT_CODE           0x13U
#define PMBUS_COMMAND_RESTORE_DEFAULT_CODE         0x14U
#define PMBUS_COMMAND_STORE_USER_ALL               0x15U
#define PMBUS_COMMAND_RESTORE_USER_ALL             0x16U
#define PMBUS_COMMAND_STORE_USER_CODE              0x17U
#define PMBUS_COMMAND_RESTORE_USER_CODE            0x18U
#define PMBUS_COMMAND_CAPABILITY                   0x19U
#define PMBUS_COMMAND_QUERY                        0x1AU
#define PMBUS_COMMAND_SMBALERT_MASK                0x1BU
#define PMBUS_COMMAND_VOUT_MODE                    0x20U
#define PMBUS_COMMAND_VOUT_COMMAND                 0x21U
#define PMBUS_COMMAND_VOUT_TRIM                    0x22U
#define PMBUS_COMMAND_VOUT_CAL_OFFSET              0x23U
#define PMBUS_COMMAND_VOUT_MAX                     0x24U
#define PMBUS_COMMAND_VOUT_MARGIN_HIGH             0x25U
#define PMBUS_COMMAND_VOUT_MARGIN_LOW              0x26U
#define PMBUS_COMMAND_VOUT_TRANSITION_RATE         0x27U
#define PMBUS_COMMAND_VOUT_DROOP                   0x28U
#define PMBUS_COMMAND_VOUT_SCALE_LOOP              0x29U
#define PMBUS_COMMAND_VOUT_SCALE_MONITOR           0x2AU
#define PMBUS_COMMAND_VOUT_MIN                     0x2BU
#define PMBUS_COMMAND_COEFFICIENTS                 0x30U
#define PMBUS_COMMAND_POUT_MAX                     0x31U
#define PMBUS_COMMAND_MAX_DUTY                     0x32U
#define PMBUS_COMMAND_FREQUENCY_SWITCH             0x33U
#define PMBUS_COMMAND_POWER_MODE                   0x34U
#define PMBUS_COMMAND_VIN_ON                       0x35U
#define PMBUS_COMMAND_VIN_OFF                      0x36U
#define PMBUS_COMMAND_INTERLEAVE                   0x37U
#define PMBUS_COMMAND_IOUT_CAL_GAIN                0x38U
#define PMBUS_COMMAND_IOUT_CAL_OFFSET              0x39U
#define PMBUS_COMMAND_FAN_CONFIG_1_2               0x3AU
#define PMBUS_COMMAND_FAN_COMMAND_1                0x3BU
#define PMBUS_COMMAND_FAN_COMMAND_2                0x3CU
#define PMBUS_COMMAND_FAN_CONFIG_3_4               0x3DU
#define PMBUS_COMMAND_FAN_COMMAND_3                0x3EU
#define PMBUS_COMMAND_FAN_COMMAND_4                0x3FU
#define PMBUS_COMMAND_VOUT_OV_FAULT_LIMIT          0x40U
#define PMBUS_COMMAND_VOUT_OV_FAULT_RESPONSE       0x41U
#define PMBUS_COMMAND_VOUT_OV_WARN_LIMIT           0x42U
#define PMBUS_COMMAND_VOUT_UV_WARN_LIMIT           0x43U
#define PMBUS_COMMAND_VOUT_UV_FAULT_LIMIT          0x44U
#define PMBUS_COMMAND_VOUT_UV_FAULT_RESPONSE       0x45U
#define PMBUS_COMMAND_IOUT_OC_FAULT_LIMIT          0x46U
#define PMBUS_COMMAND_IOUT_OC_FAULT_RESPONSE       0x47U
#define PMBUS_COMMAND_IOUT_OC_LV_FAULT_LIMIT       0x48U
#define PMBUS_COMMAND_IOUT_OC_LV_FAULT_RESPONSE    0x49U
#define PMBUS_COMMAND_IOUT_OC_WARN_LIMIT           0x4AU
#define PMBUS_COMMAND_IOUT_UC_FAULT_LIMIT          0x4BU
#define PMBUS_COMMAND_IOUT_UC_FAULT_RESPONSE       0x4CU
#define PMBUS_COMMAND_OT_FAULT_LIMIT               0x4FU
#define PMBUS_COMMAND_OT_FAULT_RESPONSE            0x50U
#define PMBUS_COMMAND_OT_WARN_LIMIT                0x51U
#define PMBUS_COMMAND_UT_WARN_LIMIT                0x52U
#define PMBUS_COMMAND_UT_FAULT_LIMIT               0x53U
#define PMBUS_COMMAND_UT_FAULT_RESPONSE            0x54U
#define PMBUS_COMMAND_VIN_OV_FAULT_LIMIT           0x55U
#define PMBUS_COMMAND_VIN_OV_FAULT_RESPONSE        0x56U
#define PMBUS_COMMAND_VIN_OV_WARN_LIMIT            0x57U
#define PMBUS_COMMAND_VIN_UV_WARN_LIMIT            0x58U
#define PMBUS_COMMAND_VIN_UV_FAULT_LIMIT           0x59U
#define PMBUS_COMMAND_VIN_UV_FAULT_RESPONSE        0x5AU
#define PMBUS_COMMAND_IIN_OC_FAULT_LIMIT           0x5BU
#define PMBUS_COMMAND_IIN_OC_FAULT_RESPONSE        0x5CU
#define PMBUS_COMMAND_IIN_OC_WARN_LIMIT            0x5DU
#define PMBUS_COMMAND_POWER_GOOD_ON                0x5EU
#define PMBUS_COMMAND_POWER_GOOD_OFF               0x5FU
#define PMBUS_COMMAND_TON_DELAY                    0x60U
#define PMBUS_COMMAND_TON_RISE                     0x61U
#define PMBUS_COMMAND_TON_MAX_FAULT_LIMIT          0x62U
#define PMBUS_COMMAND_TON_MAX_FAULT_RESPONSE       0x63U
#define PMBUS_COMMAND_TOFF_DELAY                   0x64U
#define PMBUS_COMMAND_TOFF_FALL                    0x65U
#define PMBUS_COMMAND_TOFF_MAX_WARN_LIMIT          0x66U
#define PMBUS_COMMAND_POUT_OP_FAULT_LIMIT          0x68U
#define PMBUS_COMMAND_POUT_OP_FAULT_RESPONSE       0x69U
#define PMBUS_COMMAND_POUT_OP_WARN_LIMIT           0x6AU
#define PMBUS_COMMAND_PIN_OP_WARN_LIMIT            0x6BU
#define PMBUS_COMMAND_STATUS_BYTE                  0x78U
#define PMBUS_COMMAND_STATUS_WORD                  0x79U
#define PMBUS_COMMAND_STATUS_VOUT                  0x7AU
#define PMBUS_COMMAND_STATUS_IOUT                  0x7BU
#define PMBUS_COMMAND_STATUS_INPUT                 0x7CU
#define PMBUS_COMMAND_STATUS_TEMPERATURE           0x7DU
#define PMBUS_COMMAND_STATUS_CML                   0x7EU
#define PMBUS_COMMAND_STATUS_OTHER                 0x7FU
#define PMBUS_COMMAND_STATUS_MFR_SPECIFIC          0x80U
#define PMBUS_COMMAND_STATUS_FANS_1_2              0x81U
#define PMBUS_COMMAND_STATUS_FANS_3_4              0x82U
#define PMBUS_COMMAND_READ_KWH_IN                  0x83U
#define PMBUS_COMMAND_READ_KWH_OUT                 0x84U
#define PMBUS_COMMAND_READ_KWH_CONFIG              0x85U
#define PMBUS_COMMAND_READ_EIN                     0x86U
#define PMBUS_COMMAND_READ_EOUT                    0x87U
#define PMBUS_COMMAND_READ_VIN                     0x88U
#define PMBUS_COMMAND_READ_IIN                     0x89U
#define PMBUS_COMMAND_READ_VCAP                    0x8AU
#define PMBUS_COMMAND_READ_VOUT                    0x8BU
#define PMBUS_COMMAND_READ_IOUT                    0x8CU
#define PMBUS_COMMAND_READ_TEMPERATURE_1           0x8DU
#define PMBUS_COMMAND_READ_TEMPERATURE_2           0x8EU
#define PMBUS_COMMAND_READ_TEMPERATURE_3           0x8FU
#define PMBUS_COMMAND_READ_FAN_SPEED_1             0x90U
#define PMBUS_COMMAND_READ_FAN_SPEED_2             0x91U
#define PMBUS_COMMAND_READ_FAN_SPEED_3             0x92U
#define PMBUS_COMMAND_READ_FAN_SPEED_4             0x93U
#define PMBUS_COMMAND_READ_DUTY_CYCLE              0x94U
#define PMBUS_COMMAND_READ_FREQUENCY               0x95U
#define PMBUS_COMMAND_READ_POUT                    0x96U
#define PMBUS_COMMAND_READ_PIN                     0x97U
#define PMBUS_COMMAND_PMBUS_REVISION               0x98U
#define PMBUS_COMMAND_MFR_ID                       0x99U
#define PMBUS_COMMAND_MFR_MODEL                    0x9AU
#define PMBUS_COMMAND_MFR_REVISION                 0x9BU
#define PMBUS_COMMAND_MFR_LOCATION                 0x9CU
#define PMBUS_COMMAND_MFR_DATE                     0x9DU
#define PMBUS_COMMAND_MFR_SERIAL                   0x9EU
#define PMBUS_COMMAND_APP_PROFILE_SUPPORT          0x9FU
#define PMBUS_COMMAND_MFR_VIN_MIN                  0xA0U
#define PMBUS_COMMAND_MFR_VIN_MAX                  0xA1U
#define PMBUS_COMMAND_MFR_IIN_MAX                  0xA2U
#define PMBUS_COMMAND_MFR_PIN_MAX                  0xA3U
#define PMBUS_COMMAND_MFR_VOUT_MIN                 0xA4U
#define PMBUS_COMMAND_MFR_VOUT_MAX                 0xA5U
#define PMBUS_COMMAND_MFR_IOUT_MAX                 0xA6U
#define PMBUS_COMMAND_MFR_POUT_MAX                 0xA7U
#define PMBUS_COMMAND_MFR_TAMBIENT_MAX             0xA8U
#define PMBUS_COMMAND_MFR_TAMBIENT_MIN             0xA9U
#define PMBUS_COMMAND_MFR_EFFICIENCY_LL            0xAAU
#define PMBUS_COMMAND_MFR_EFFICIENCY_HL            0xABU
#define PMBUS_COMMAND_MFR_PIN_ACCURACY             0xACU
#define PMBUS_COMMAND_IC_DEVICE_ID                 0xADU
#define PMBUS_COMMAND_IC_DEVICE_REV                0xAEU
#define PMBUS_COMMAND_USER_DATA_00                 0xB0U
#define PMBUS_COMMAND_USER_DATA_01                 0xB1U
#define PMBUS_COMMAND_USER_DATA_02                 0xB2U
#define PMBUS_COMMAND_USER_DATA_03                 0xB3U
#define PMBUS_COMMAND_USER_DATA_04                 0xB4U
#define PMBUS_COMMAND_USER_DATA_05                 0xB5U
#define PMBUS_COMMAND_USER_DATA_06                 0xB6U
#define PMBUS_COMMAND_USER_DATA_07                 0xB7U
#define PMBUS_COMMAND_USER_DATA_08                 0xB8U
#define PMBUS_COMMAND_USER_DATA_09                 0xB9U
#define PMBUS_COMMAND_USER_DATA_10                 0xBAU
#define PMBUS_COMMAND_USER_DATA_11                 0xBBU
#define PMBUS_COMMAND_USER_DATA_12                 0xBCU
#define PMBUS_COMMAND_USER_DATA_13                 0xBDU
#define PMBUS_COMMAND_USER_DATA_14                 0xBEU
#define PMBUS_COMMAND_USER_DATA_15                 0xBFU
#define PMBUS_COMMAND_MFR_MAX_TEMP_1               0xC0U
#define PMBUS_COMMAND_MFR_MAX_TEMP_2               0xC1U
#define PMBUS_COMMAND_MFR_MAX_TEMP_3               0xC2U
#define PMBUS_COMMAND_MFR_SPECIFIC_C4              0xC4U
#define PMBUS_COMMAND_MFR_SPECIFIC_C5              0xC5U
#define PMBUS_COMMAND_MFR_SPECIFIC_C6              0xC6U
#define PMBUS_COMMAND_MFR_SPECIFIC_C7              0xC7U
#define PMBUS_COMMAND_MFR_SPECIFIC_C8              0xC8U
#define PMBUS_COMMAND_MFR_SPECIFIC_C9              0xC9U
#define PMBUS_COMMAND_MFR_SPECIFIC_CA              0xCAU
#define PMBUS_COMMAND_MFR_SPECIFIC_CB              0xCBU
#define PMBUS_COMMAND_MFR_SPECIFIC_CC              0xCCU
#define PMBUS_COMMAND_MFR_SPECIFIC_CD              0xCDU
#define PMBUS_COMMAND_MFR_SPECIFIC_CE              0xCEU
#define PMBUS_COMMAND_MFR_SPECIFIC_CF              0xCFU
#define PMBUS_COMMAND_MFR_COLD_REDUNDANCY_CONFIG   0xD0U
#define PMBUS_COMMAND_MFR_SPECIFIC_D1              0xD1U
#define PMBUS_COMMAND_MFR_SPECIFIC_D2              0xD2U
#define PMBUS_COMMAND_MFR_SPECIFIC_D3              0xD3U
#define PMBUS_COMMAND_MFR_HW_COMPATIBILITY         0xD4U
#define PMBUS_COMMAND_MFR_FWUPLOAD_CAPABILITY      0xD5U
#define PMBUS_COMMAND_MFR_FWUPLOAD_MODE            0xD6U
#define PMBUS_COMMAND_MFR_FWUPLOAD                 0xD7U
#define PMBUS_COMMAND_MFR_FWUPLOAD_STATUS          0xD8U
#define PMBUS_COMMAND_MFR_FW_REVISION              0xD9U
#define PMBUS_COMMAND_MFR_SPECIFIC_DA              0xDAU
#define PMBUS_COMMAND_MFR_FRU_PROTECTION           0xDBU
#define PMBUS_COMMAND_MFR_BLACKBOX                 0xDCU
#define PMBUS_COMMAND_MFR_REAL_TIME_BLACK_BOX      0xDDU
#define PMBUS_COMMAND_MFR_SYSTEM_BLACK_BOX         0xDEU
#define PMBUS_COMMAND_MFR_SPECIFIC_DF              0xDFU
#define PMBUS_COMMAND_MFR_SPECIFIC_E0              0xE0U
#define PMBUS_COMMAND_MFR_SPECIFIC_E1              0xE1U
#define PMBUS_COMMAND_MFR_SPECIFIC_E2              0xE2U
#define PMBUS_COMMAND_MFR_SPECIFIC_E3              0xE3U
#define PMBUS_COMMAND_MFR_SPECIFIC_E4              0xE4U
#define PMBUS_COMMAND_MFR_SPECIFIC_E5              0xE5U
#define PMBUS_COMMAND_MFR_SPECIFIC_E6              0xE6U
#define PMBUS_COMMAND_MFR_SPECIFIC_E7              0xE7U
#define PMBUS_COMMAND_MFR_SPECIFIC_E8              0xE8U
#define PMBUS_COMMAND_MFR_SPECIFIC_E9              0xE9U
#define PMBUS_COMMAND_MFR_SPECIFIC_EA              0xEAU
#define PMBUS_COMMAND_MFR_SPECIFIC_EB              0xEBU
#define PMBUS_COMMAND_MFR_SPECIFIC_EC              0xECU
#define PMBUS_COMMAND_MFR_SPECIFIC_ED              0xEDU
#define PMBUS_COMMAND_MFR_SPECIFIC_EE              0xEEU
#define PMBUS_COMMAND_MFR_SPECIFIC_EF              0xEFU
#define PMBUS_COMMAND_MFR_PWOK_WARNING_TIME        0xF0U
#define PMBUS_COMMAND_MFR_MAX_IOUT_CAPABILITY      0xF1U
#define PMBUS_COMMAND_MFR_SPECIFIC_F2              0xF2U
#define PMBUS_COMMAND_MFR_SPECIFIC_F3              0xF3U
#define PMBUS_COMMAND_MFR_SPECIFIC_F4              0xF4U
#define PMBUS_COMMAND_MFR_SPECIFIC_F5              0xF5U
#define PMBUS_COMMAND_MFR_SPECIFIC_F6              0xF6U
#define PMBUS_COMMAND_MFR_SPECIFIC_F7              0xF7U
#define PMBUS_COMMAND_MFR_SPECIFIC_F8              0xF8U
#define PMBUS_COMMAND_MFR_SPECIFIC_F9              0xF9U
#define PMBUS_COMMAND_MFR_SPECIFIC_FA              0xFAU
#define PMBUS_COMMAND_MFR_SPECIFIC_FB              0xFBU
#define PMBUS_COMMAND_MFR_SPECIFIC_FC              0xFCU
#define PMBUS_COMMAND_MFR_SPECIFIC_FD              0xFDU
#define PMBUS_COMMAND_MFR_SPECIFIC_COMMAND_EXT     0xFEU
#define PMBUS_COMMAND_PMBUS_COMMAND_EXT            0xFFU

/* M-CRPS 1.06 Table 12-38 aliases.
   Keep these names separate from generic USER_DATA/MFR_SPECIFIC names so
   dispatch, debug logs, and product-binding TODOs can point to the public
   M-CRPS command names directly. */
#define PMBUS_COMMAND_MFR_EFFICIENCY_DATA          PMBUS_COMMAND_USER_DATA_03
#define PMBUS_COMMAND_MFR_READ_CONFIG_FILE_SIZE    PMBUS_COMMAND_MFR_SPECIFIC_D1
#define PMBUS_COMMAND_MFR_READ_CONFIG_BLOCK_SIZE   PMBUS_COMMAND_MFR_SPECIFIC_D2
#define PMBUS_COMMAND_MFR_READ_CONFIG_FILE         PMBUS_COMMAND_MFR_SPECIFIC_D3
#define PMBUS_COMMAND_MFR_SPDM                     PMBUS_COMMAND_MFR_SPECIFIC_DA
#define PMBUS_COMMAND_MFR_BLACK_BOX_CONFIG         PMBUS_COMMAND_MFR_SPECIFIC_DF
#define PMBUS_COMMAND_MFR_CLEAR_BLACK_BOX          PMBUS_COMMAND_MFR_SPECIFIC_E0
#define PMBUS_COMMAND_MFR_LINE_STATUS              PMBUS_COMMAND_MFR_SPECIFIC_E1
#define PMBUS_COMMAND_MFR_SYSTEM_LED_CNTL          PMBUS_COMMAND_MFR_SPECIFIC_E2
#define PMBUS_COMMAND_MFR_FWUPLOAD_BLOCK_SIZE      PMBUS_COMMAND_MFR_SPECIFIC_E3
#define PMBUS_COMMAND_MFR_EN_STATUS_SIMULATION_CMD PMBUS_COMMAND_MFR_SPECIFIC_E4
#define PMBUS_COMMAND_MFR_PEAK_CURRENT_RECORD      PMBUS_COMMAND_MFR_SPECIFIC_E9
#define PMBUS_COMMAND_MFR_COMPONENT_ID             PMBUS_COMMAND_MFR_SPECIFIC_EB
#define PMBUS_COMMAND_MFR_TOT_POUT_MAX             PMBUS_COMMAND_MFR_SPECIFIC_EC
#define PMBUS_COMMAND_MFR_VOUT_MARGINING           PMBUS_COMMAND_MFR_SPECIFIC_ED
#define PMBUS_COMMAND_MFR_OCWPL1_SETTING           PMBUS_COMMAND_MFR_SPECIFIC_EE
#define PMBUS_COMMAND_MFR_FPC_MAIN_MIN_OFF_TIME    PMBUS_COMMAND_MFR_SPECIFIC_F2
#define PMBUS_COMMAND_MFR_FPC_12VSB_MIN_OFF_TIME   PMBUS_COMMAND_MFR_SPECIFIC_F3

/*
    PMBus 1.3.1 Part II Table 2: VOUT_MODE byte format.
    Bit 7 selects absolute/relative mode. Bits 6:5 select the voltage data
    format. Bits 4:0 are format-specific parameter bits.
*/
#define PMBUS_VOUT_MODE_RELATIVE_MASK              0x80U
#define PMBUS_VOUT_MODE_FORMAT_MASK                0x60U
#define PMBUS_VOUT_MODE_PARAMETER_MASK             0x1FU
#define PMBUS_VOUT_MODE_FORMAT_ULINEAR16           0x00U
#define PMBUS_VOUT_MODE_FORMAT_VID                 0x20U
#define PMBUS_VOUT_MODE_FORMAT_DIRECT              0x40U
#define PMBUS_VOUT_MODE_FORMAT_IEEE_HALF           0x60U

#define PMBUS_STATUS_BYTE_BUSY                       0x80U
#define PMBUS_STATUS_BYTE_OFF                        0x40U
#define PMBUS_STATUS_BYTE_VOUT_OV_FAULT              0x20U
#define PMBUS_STATUS_BYTE_IOUT_OC_FAULT              0x10U
#define PMBUS_STATUS_BYTE_VIN_UV_FAULT               0x08U
#define PMBUS_STATUS_BYTE_TEMPERATURE                0x04U
#define PMBUS_STATUS_BYTE_CML                        0x02U
#define PMBUS_STATUS_BYTE_NONE_OF_THE_ABOVE          0x01U

#define PMBUS_STATUS_WORD_VOUT                       0x8000U
#define PMBUS_STATUS_WORD_IOUT_POUT                  0x4000U
#define PMBUS_STATUS_WORD_INPUT                      0x2000U
#define PMBUS_STATUS_WORD_MFR_SPECIFIC               0x1000U
#define PMBUS_STATUS_WORD_PG_STATUS                  0x0800U
#define PMBUS_STATUS_WORD_FANS                       0x0400U
#define PMBUS_STATUS_WORD_OTHER                      0x0200U
#define PMBUS_STATUS_WORD_UNKNOWN                    0x0100U
#define PMBUS_STATUS_WORD_LOW_BYTE_CML               0x0002U

#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_COMMAND_RECEIVED 0x80U
#define PMBUS_STATUS_CML_INVALID_OR_UNSUPPORTED_DATA_RECEIVED    0x40U
#define PMBUS_STATUS_CML_PACKET_ERROR_CHECK_FAILED               0x20U
#define PMBUS_STATUS_CML_MEMORY_FAULT_DETECTED                   0x10U
#define PMBUS_STATUS_CML_PROCESSOR_FAULT_DETECTED                0x08U
#define PMBUS_STATUS_CML_OTHER_COMMUNICATION_FAULT               0x02U
#define PMBUS_STATUS_CML_OTHER_MEMORY_OR_LOGIC_FAULT             0x01U

#define PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT         0x20U
#define PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT         0x10U
#define PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT            0x08U
#define PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT            0x04U
#define PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT             0x02U
#define PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT              0x01U

#define PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS                       0xFFU

#define PMBUS_STATUS_VOUT_VOUT_OV_FAULT               0x80U
#define PMBUS_STATUS_VOUT_VOUT_OV_WARNING             0x40U
#define PMBUS_STATUS_VOUT_VOUT_UV_WARNING             0x20U
#define PMBUS_STATUS_VOUT_VOUT_UV_FAULT               0x10U
#define PMBUS_STATUS_VOUT_VOUT_MAX_MIN_WARNING        0x08U
#define PMBUS_STATUS_VOUT_TON_MAX_FAULT               0x04U
#define PMBUS_STATUS_VOUT_TOFF_MAX_WARNING            0x02U
#define PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR         0x01U

#define PMBUS_STATUS_IOUT_IOUT_OC_FAULT               0x80U
#define PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT            0x40U
#define PMBUS_STATUS_IOUT_IOUT_OC_WARNING             0x20U
#define PMBUS_STATUS_IOUT_IOUT_UC_FAULT               0x10U
#define PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT         0x08U
#define PMBUS_STATUS_IOUT_IN_POWER_LIMITING_MODE      0x04U
#define PMBUS_STATUS_IOUT_POUT_OP_FAULT               0x02U
#define PMBUS_STATUS_IOUT_POUT_OP_WARNING             0x01U

#define PMBUS_STATUS_INPUT_VIN_OV_FAULT                         0x80U
#define PMBUS_STATUS_INPUT_VIN_OV_WARNING                       0x40U
#define PMBUS_STATUS_INPUT_VIN_UV_WARNING                       0x20U
#define PMBUS_STATUS_INPUT_VIN_UV_FAULT                         0x10U
#define PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE 0x08U
#define PMBUS_STATUS_INPUT_IIN_OC_FAULT                         0x04U
#define PMBUS_STATUS_INPUT_IIN_OC_WARNING                       0x02U
#define PMBUS_STATUS_INPUT_PIN_OP_WARNING                       0x01U

#define PMBUS_STATUS_TEMPERATURE_OT_FAULT            0x80U
#define PMBUS_STATUS_TEMPERATURE_OT_WARNING          0x40U
#define PMBUS_STATUS_TEMPERATURE_UT_WARNING          0x20U
#define PMBUS_STATUS_TEMPERATURE_UT_FAULT            0x10U

#define PMBUS_STATUS_FANS_1_2_FAN_1_FAULT            0x80U
#define PMBUS_STATUS_FANS_1_2_FAN_2_FAULT            0x40U
#define PMBUS_STATUS_FANS_1_2_FAN_1_WARNING          0x20U
#define PMBUS_STATUS_FANS_1_2_FAN_2_WARNING          0x10U
#define PMBUS_STATUS_FANS_1_2_FAN_1_SPEED_OVERRIDDEN 0x08U
#define PMBUS_STATUS_FANS_1_2_FAN_2_SPEED_OVERRIDDEN 0x04U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT          0x02U
#define PMBUS_STATUS_FANS_1_2_AIRFLOW_WARNING        0x01U

#define PMBUS_STATUS_VOUT_FAULT_MASK                 (PMBUS_STATUS_VOUT_VOUT_OV_FAULT | PMBUS_STATUS_VOUT_VOUT_UV_FAULT | PMBUS_STATUS_VOUT_TON_MAX_FAULT | PMBUS_STATUS_VOUT_VOUT_TRACKING_ERROR)
#define PMBUS_STATUS_IOUT_FAULT_MASK                 (PMBUS_STATUS_IOUT_IOUT_OC_FAULT | PMBUS_STATUS_IOUT_IOUT_OC_LV_FAULT | PMBUS_STATUS_IOUT_IOUT_UC_FAULT | PMBUS_STATUS_IOUT_CURRENT_SHARE_FAULT | PMBUS_STATUS_IOUT_POUT_OP_FAULT)
#define PMBUS_STATUS_INPUT_FAULT_MASK                (PMBUS_STATUS_INPUT_VIN_OV_FAULT | PMBUS_STATUS_INPUT_VIN_UV_FAULT | PMBUS_STATUS_INPUT_UNIT_OFF_FOR_INSUFFICIENT_INPUT_VOLTAGE | PMBUS_STATUS_INPUT_IIN_OC_FAULT)
#define PMBUS_STATUS_TEMPERATURE_FAULT_MASK          (PMBUS_STATUS_TEMPERATURE_OT_FAULT | PMBUS_STATUS_TEMPERATURE_UT_FAULT)
#define PMBUS_STATUS_FANS_1_2_FAULT_MASK             (PMBUS_STATUS_FANS_1_2_FAN_1_FAULT | PMBUS_STATUS_FANS_1_2_FAN_2_FAULT | PMBUS_STATUS_FANS_1_2_AIRFLOW_FAULT)
#define PMBUS_STATUS_CML_FAULT_MASK                  0xFFU
#define PMBUS_STATUS_OTHER_FAULT_MASK                (PMBUS_STATUS_OTHER_INPUT_A_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_B_FUSE_OR_BREAKER_FAULT | PMBUS_STATUS_OTHER_INPUT_A_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_INPUT_B_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_OUTPUT_ORING_DEVICE_FAULT | PMBUS_STATUS_OTHER_FIRST_TO_ASSERT_SMBALERT)
#define PMBUS_STATUS_MFR_SPECIFIC_FAULT_MASK         PMBUS_STATUS_MFR_SPECIFIC_ALL_BITS

#define PMBUS_BLACKBOX_BLOCK_SIZE                    32U
#define PMBUS_MFR_CONFIG_FILE_SIZE_BLOCK_SIZE        4U
#define PMBUS_MFR_READ_CONFIG_FILE_BLOCK_SIZE        16U
#define PMBUS_MFR_EFFICIENCY_DATA_BLOCK_SIZE         8U
#define PMBUS_MFR_FW_REVISION_BLOCK_SIZE             7U
#define PMBUS_MFR_SPDM_BLOCK_SIZE                    8U
#define PMBUS_MFR_REAL_TIME_BLACK_BOX_SIZE           4U
#define PMBUS_MFR_SYSTEM_BLACK_BOX_SIZE              32U
#define PMBUS_MFR_MAX_IOUT_CAPABILITY_SIZE           14U
#define PMBUS_MFR_PEAK_CURRENT_RECORD_SIZE           8U
#define PMBUS_MFR_COMPONENT_ID_SIZE                  12U
#define PMBUS_MFR_OCWPL1_SETTING_SIZE                8U

#define PMBUS_FWUPLOAD_STATUS_COMPLETE               0x0001U
#define PMBUS_FWUPLOAD_STATUS_IN_PROGRESS            0x0002U
#define PMBUS_FWUPLOAD_STATUS_BAD_IMAGE              0x0004U
#define PMBUS_FWUPLOAD_STATUS_UNSUPPORTED            0x0010U

#define PMBUS_FWUPLOAD_HEADER_SIZE                   4U
#define PMBUS_FWUPLOAD_FLAG_FINAL_BLOCK              0x01U

#define PMBUS_I2C_STATUS_BUS_ERROR                   0x00U
#define PMBUS_I2C_STATUS_SLA_W_ACK                   0x60U
#define PMBUS_I2C_STATUS_DATA_RX_ACK                 0x80U
#define PMBUS_I2C_STATUS_DATA_RX_NACK                0x88U
#define PMBUS_I2C_STATUS_STOP_RESTART                0xA0U
#define PMBUS_I2C_STATUS_SLA_R_ACK                   0xA8U
#define PMBUS_I2C_STATUS_DATA_TX_ACK                 0xB8U
#define PMBUS_I2C_STATUS_DATA_TX_NACK                0xC0U
#define PMBUS_I2C_STATUS_LAST_TX_ACK                 0xC8U

#endif
